version: '3.8'
services:
  app:
    image: mySpringApp
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=DEV
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: example